version: '3.6'

services:
  elasticsearch:
    container_name: elasticsearch
    image: xiaoxuan6/elasticsearch:7.17.6
    restart: on-failure
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    environment:
      - TZ=$TZ
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    # HEALTHCHECK 只可以出现一次，如果写了多个，只有最后一个生效。
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:9200"]
      # interval: 3m # 两次健康检查的间隔，默认为 30 秒，单位(h/m/s)；
      # timeout: 30s # 健康检查命令运行超时时间，如果超过这个时间，本次健康检查就被视为失败，默认 30 秒，单位(h/m/s)；
      # retries: 3 # 当连续失败指定次数后，则将容器状态视为 unhealthy，默认 3 次。
      # start_period: 40s # 该start_period选项是在文件格式 3.4 中添加的
    networks:
      elasticsearch:

  kibana:
    container_name: kibana
    image: kibana:7.17.6
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      elasticsearch:

  php:
    container_name: php
    image: xiaoxuan6/php:7.4-fpm-alpine
    restart: on-failure
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html
    networks:
      elasticsearch:

  mysql:
    container_name: mysql
    image: mysql:5.7.40
    restart: on-failure
    ports:
      - 3306:3306
    environment: # 环境变量
      MYSQL_DATABASE: "elasticsearch"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      # mysql -u 用户名 -p密码 -h 服务器IP地址 -P 服务器端MySQL端口号 -D 数据库名
      #test: [ "CMD", "mysql", "-h", "127.0.0.1", "-P", "3306", "-u", "root", "-p", "root", "-e", "SELECT 1", "cache" ]
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      retries: 5
    networks:
      elasticsearch:

  nginx:
    container_name: nginx
    image: nginx
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      - php
      - elasticsearch
      - mysql
      # condition在版本 3.0 到 3.8 中删除了 compose 规范，但现在又回来了！
      # 目前无法使用，未知错误。使用 version 3.9 同样报错
#      php:
#        condition: service_started
#      elasticsearch:
#        condition: service_healthy
#      mysql:
#        condition: service_healthy
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      elasticsearch:

  artisan:
    container_name: artisan
    image: xiaoxuan6/php:7.4-fpm-alpine
    volumes:
      - ./:/var/www/html
    depends_on:
      - elasticsearch
      - mysql
    working_dir: /var/www/html
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      elasticsearch:

networks:
  elasticsearch:
