version: '3.6'

services:
  elasticsearch:
    container_name: elasticsearch
    image: xiaoxuan6/elasticsearch:7.17.6
    restart: on-failure
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    environment:
      - TZ=$TZ
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      elasticsearch:

  kibana:
    container_name: kibana
    image: kibana:7.17.6
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      elasticsearch:

  mysql:
    container_name: mysql
    image: mysql:5.7.40
    restart: on-failure
    ports:
      - 3306:3306
    environment: # 环境变量
      MYSQL_DATABASE: "elasticsearch"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      elasticsearch:

  app:
    build:
      context: .
    container_name: app
    ports:
      - 80:80
    volumes:
#      - ./:/var/www/html # 这里有个坑，dockerfile 中执行了 composer install 与挂载目录不能同时存在，否则 composer install 无法生成 vendor 目录，以挂载目录为准
      - ./default.conf:/etc/apache2/sites-available/000-default.conf
#      - ./entrypoint.sh:/usr/local/bin/entrypoint
    depends_on:
      - mysql
      - elasticsearch
    networks:
      elasticsearch:

networks:
  elasticsearch:
